### ISSUE TITLE
Consider changing default cork_install_path

### ISSUE THREAD

**Issue by vbauerster** [topisani/cork.kak#16]
What is problem with default path?

https://github.com/topisani/cork.kak/blob/b8f2e0ce43771837d1f9a122976c8dc098c07334/cork.sh#L209

It's under `kak` namespace, which may seems logical at first, but may lead to problems if kakoune installed to the same directory. Let me elaborate, building kakoune from source is pretty common practice and if user went with `PREFIX=$HOME/.local make install` then cork and kakoune will share the same directory. It's not a big deal until user decides to reinstall kakoune for example with purpose to be system wide available. So in my case I did:

```
# pwd is kakoune source
PREFIX=$HOME/.local make uninstall
make install
```

I think you already guessed what happened, cork directory nuked as well. This might be not a big deal, but with slow connection like I have it took considerable amount of time to restore all plugins. This wouldn't happen if `cork` installed plugins into its own namespace directory like `%opt{cork_xdg_data_home_path}/cork/plugins` for example.

**Comment by topisani** [comment]
Good point, done!
